language: c
sudo: required
dist: trusty
compiler: gcc
os: linux

env:
  global:
    - MARIADB_URL=https://downloads.mariadb.org/interstitial/mariadb-10.1.12/bintar-linux-glibc_214-x86_64/mariadb-10.1.12-linux-glibc_214-x86_64.tar.gz/from/http%3A//mirror.netinch.com/pub/mariadb/
    - MARIADB_TAR=mariadb-10.1.12-linux-glibc_214-x86_64.tar.gz
    - MARIADB_DIR=mariadb-10.1.12-linux-glibc_214-x86_64

# prepare the environment
before_script:
  # get mariadb packages from mariadb.org
  - chmod +x .travis/download_mariadb.sh
  - .travis/download_mariadb.sh

# actual compilation commands
script:
  - chmod +x .travis/build_maxscale.sh
  - .travis/build_maxscale.sh

#some dependencies
addons:
  apt:
    packages:
      - libaio-dev
      - libpcre3-dev
      - doxygen
      - pandoc

#notify on irc
notifications:
  irc: "chat.freenode.net#rasmus-test"